[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-airflow-project"
version = "0.1.0"
description = "A sample project using Airflow"
requires-python = ">=3.12"
dependencies = [
  "faker>=40.21.0",
  "duckdb==1.5.3",
]

[tool.setuptools.packages.find]
exclude = ["dags*", "logs*"]

[dependency-groups]
dev = [
  "aiohttp>=3.14.1",
  "apache-airflow>=3.2.2",
  "apache-airflow-providers-cncf-kubernetes",
  "beautifulsoup4>=4.15.0",
  "ipykernel>=7.3.0",
  "ipython>=9.14.1",
  "playwright>=1.60.0",
  "pre-commit>=4.6.0",
  "ruff>=0.15.17",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/my-airflow-project"
"Bug Tracker" = "https://github.com/yourusername/my-airflow-project/issues"
