apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-output-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/task-outputs  # Path on the Minikube node


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-outputs-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
