services:
  airflow:
    build:
      context: ../../
      dockerfile: packages/airflow-pipelines/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./task-outputs/:/opt/airflow/task-outputs
    environment:
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
    command: standalone
