x-db-env: &db-env
  POSTGRES_USER: postgres
  POSTGRES_DB: crawler
  POSTGRES_PASSWORD: 1234

services:
  crawler:
    container_name: wikipedia_crawler
    build:
      context: ../../../
      dockerfile: apps/web-crawler/wikipedia/Dockerfile
    environment:
      <<: *db-env
      OUTPUT_DIR: /app/crawled_data
      REDIS_HOST: redis
      POSTGRES_HOST: postgres # postgres service name, not localhost
      PYTHONUNBUFFERED: "1"
    command: python -m web_crawler.wikipedia.postgres.db
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  redis:
    container_name: crawler_redis
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    container_name: crawler_postgres
    image: postgres:18-alpine
    environment:
      <<: *db-env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s

volumes:
  redis-data:
  db-data:

